{
 "title": "Demo TX",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TX Logs",
   "type": "table",
   "gridPos": { "h": 23, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM \"bank-transactions\""
    }
   ]
  },
  {
   "title": "Tx counts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as \"TX size\"\nFROM\n  \"bank-transactions\"\n"
    }
   ]
  },
  {
   "title": "Rejected Tx counts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as \"Rejected TX size\"\nFROM\n  \"bank-transactions\"\nwhere \"state\" = 'REJECTED'\n"
    }
   ]
  }
 ]
}